name: compile and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: # This will make the workflow run for below specific paths only
      - ".github/workflows/ci.yml"
      - "public/**"
      - "src/**"
      - "tests/**"

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Getting the code
        uses: actions/checkout@v4.2.2

      - name: setup nodejs
        uses: actions/setup-node@v3.9.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Getting the dependencies
        run: npm install

      - name: Start development server
        run: npm run dev &
        timeout-minutes: 2

      - name: Run e2e tests
        run: |
          npm install
          npx playwright install chromium
          npm run test:e2e e2e/features
        working-directory: tests/
        timeout-minutes: 5

      - name: compile
        run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build # Name of the artifact
          path: dist # Path to the file or directory to upload (where the build was created)
